// src/utils/attachmentProcessor.js
// ============================================================
// ATTACHMENT PREPROCESSOR
//
// Images  → fetch + encode to Base64 inline data URL
// PDFs    → extract text using pdf-parse
// Docs    → extract raw text
//
// CHAT AUDIT CHANGE (§5.8): the naming here ("Grok") is legacy from an
// earlier xAI-Grok-based integration — the product now runs on the
// Cerebras/Groq-Cloud/Mistral/OpenRouter multi-provider stack in
// multiProvider.js (note "Grok"/xAI and "Groq"/Groq Cloud are different
// providers — only the latter is actually wired up). Function names are
// kept as-is here to avoid a churn-only rename across every call site in
// chat.js; what actually changed is that images are no longer a dead end.
// `extractImageParts()` below pulls the already-fetched base64 image data
// back out in a shape multiProvider.js can attach directly to a
// vision-capable model's request. The text placeholder generated by
// buildGrokAttachmentPrompt is still produced too, and is what non-vision
// models in the fallback queue will see instead.
// ============================================================

import axios from 'axios';

/**
 * Process attachments into a format the AI can understand.
 * Returns: array of { type, content, filename, inline_data? } objects
 *
 * @param {array} attachments - file records (name/type/url)
 * @returns {array} processed attachments ready for prompt injection
 */
const classifyFile = (type = '') => {
  const t = type.toLowerCase();
  if (t.includes('image')) return 'image';
  if (t.includes('pdf')) return 'pdf';
  return 'document';
};

const EXT_MIME = {
  png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg',
  gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml',
};
const resolveMimeType = (type, filename) => {
  if (type && type.includes('/')) return type;
  const ext = filename?.split('.').pop()?.toLowerCase();
  return EXT_MIME[ext] || 'image/png';
};

// ------------------------------------------------------------------
// Token-budget caps
// ------------------------------------------------------------------
const MAX_TOTAL_ATTACHMENT_CHARS = 16000;
const MAX_HISTORY_SNIPPET_CHARS = 400;

const capProcessedAttachments = (processed, maxTotalChars = MAX_TOTAL_ATTACHMENT_CHARS) => {
  let remaining = maxTotalChars;
  const capped = [];
  let omittedCount = 0;

  for (const att of processed) {
    const size = att.content?.length || 0;

    if (remaining <= 0) {
      omittedCount += 1;
      continue;
    }

    if (size <= remaining) {
      capped.push(att);
      remaining -= size;
    } else {
      capped.push({
        ...att,
        content: `${att.content.slice(0, remaining)}\n[...truncated to stay within attachment token budget]`,
      });
      remaining = 0;
    }
  }

  if (omittedCount > 0) {
    capped.push({
      type: 'unknown',
      filename: `+${omittedCount} more file(s)`,
      content: `[${omittedCount} additional attachment(s) omitted to stay within the per-message attachment budget]`,
    });
  }

  return capped;
};

export const buildAttachmentHistorySummary = (processedAttachments, maxCharsPerFile = MAX_HISTORY_SNIPPET_CHARS) => {
  if (!processedAttachments?.length) return '';

  const parts = processedAttachments.map(att => {
    if (att.type === 'image') {
      return `[Image "${att.filename}" was attached earlier in this conversation]`;
    }
    if ((att.type === 'document' || att.type === 'pdf') && att.content) {
      const truncated = att.content.length > maxCharsPerFile;
      const snippet = att.content.slice(0, maxCharsPerFile);
      return `[Earlier attachment "${att.filename}"${truncated ? ' (truncated)' : ''}: ${snippet}]`;
    }
    return `[Attachment "${att.filename}" was referenced earlier in this conversation]`;
  });

  return `\n\n(Context from files attached earlier — condensed: ${parts.join(' ')})`;
};

export const preprocessAttachmentsForGrok = async (attachments) => {
  console.log('[AttachmentProcessor] preprocessAttachmentsForGrok called with', {
    count: attachments?.length || 0,
    attachments: attachments?.map(a => ({ name: a.name, type: a.type, hasUrl: !!a.url })),
  });

  if (!attachments?.length) return [];

  const processed = [];

  for (const file of attachments) {
    const filename = file.name;
    const url = file.url;
    const kind = classifyFile(file.type);

    console.log(`[AttachmentProcessor] Processing "${filename}"`, { rawType: file.type, kind, hasUrl: !!url });

    if (!url) {
      console.warn(`[AttachmentProcessor] "${filename}" has no url — skipping fetch, using placeholder`);
      processed.push({
        type: 'unknown',
        filename,
        content: `[File "${filename}" was attached but has no accessible URL — reference it by name if needed]`,
      });
      continue;
    }

    try {
      if (kind === 'image') {
        const base64 = await fetchAsBase64(url);
        if (base64) {
          const mimeType = resolveMimeType(file.type, filename);
          console.log(`[AttachmentProcessor] "${filename}" encoded to base64 (${base64.length} chars, mime=${mimeType})`);
          processed.push({
            type: 'image',
            filename,
            content: null,
            inline_data: `data:${mimeType};base64,${base64}`,
          });
        } else {
          console.warn(`[AttachmentProcessor] "${filename}" base64 encoding returned empty result`);
          processed.push({
            type: 'unknown',
            filename,
            content: `[Image "${filename}" could not be encoded — reference it by name if needed]`,
          });
        }
      } else if (kind === 'pdf') {
        const text = await extractPdfText(url);
        if (text) {
          console.log(`[AttachmentProcessor] "${filename}" PDF text extracted (${text.length} chars)`);
          processed.push({
            type: 'document',
            filename,
            content: text.slice(0, 8000),
          });
        } else {
          console.warn(`[AttachmentProcessor] "${filename}" PDF extraction returned no text`);
          processed.push({
            type: 'unknown',
            filename,
            content: `[PDF "${filename}" could not be read — reference it by name if needed]`,
          });
        }
      } else {
        const text = await fetchRawText(url);
        if (text) {
          console.log(`[AttachmentProcessor] "${filename}" raw text fetched (${text.length} chars)`);
          processed.push({
            type: 'document',
            filename,
            content: text.slice(0, 8000),
          });
        } else {
          console.warn(`[AttachmentProcessor] "${filename}" raw text fetch returned nothing`);
          processed.push({
            type: 'unknown',
            filename,
            content: `[File "${filename}" returned no readable content — reference it by name if needed]`,
          });
        }
      }
    } catch (err) {
      console.warn(`[AttachmentProcessor] Failed to process "${filename}":`, err.message);
      processed.push({
        type: 'unknown',
        filename,
        content: `[File "${filename}" could not be processed — reference it by name if needed]`,
      });
    }
  }

  console.log('[AttachmentProcessor] Finished. Processed', processed.length, 'of', attachments.length, 'attachments');

  const capped = capProcessedAttachments(processed);
  if (capped.length !== processed.length || capped.some((c, i) => c.content !== processed[i]?.content)) {
    console.log('[AttachmentProcessor] Applied aggregate attachment budget cap', {
      before: processed.length,
      after: capped.length,
      maxTotalChars: MAX_TOTAL_ATTACHMENT_CHARS,
    });
  }

  return capped;
};

/**
 * Build the prompt text block appended to the user's message. For images
 * this is always a text placeholder — it's the fallback description any
 * NON-vision model in the fallback queue will actually see. Vision-capable
 * models instead get the real image bytes via extractImageParts() below,
 * threaded through multiProvider.js.
 */
export const buildGrokAttachmentPrompt = (processedAttachments) => {
  if (!processedAttachments?.length) {
    console.log('[AttachmentProcessor] buildGrokAttachmentPrompt: nothing to build (empty/undefined processedAttachments)');
    return '';
  }

  const parts = processedAttachments.map(att => {
    if (att.type === 'image') {
      return `[Image attached: "${att.filename}" — if the model answering this turn supports vision it has been given the actual image; otherwise, note that you cannot see it and ask the user to describe it]`;
    }
    if (att.type === 'document' || att.type === 'pdf') {
      return `\n--- Document: "${att.filename}" ---\n${att.content}\n--- End of document ---`;
    }
    return att.content || '';
  });

  const prompt = `\n\nATTACHED FILES:\n${parts.join('\n')}`;
  console.log(`[AttachmentProcessor] buildGrokAttachmentPrompt: built prompt block of ${prompt.length} chars for ${processedAttachments.length} attachment(s)`);
  return prompt;
};

/**
 * NEW (audit §5.8): pulls the base64 image data URLs back out of an
 * already-processed attachment list, in the `{ url }[]` shape
 * multiProvider.js's vision path expects. Only ever meaningful for the
 * CURRENT turn's attachments — history re-injection uses
 * buildAttachmentHistorySummary's text-only placeholder instead, since we
 * don't want to re-pay for image tokens on every later turn.
 */
export const extractImageParts = (processedAttachments) => {
  if (!processedAttachments?.length) return [];
  return processedAttachments
    .filter(att => att.type === 'image' && att.inline_data)
    .map(att => ({ url: att.inline_data }));
};

// ──────────────────────────────────────────
// INTERNAL HELPERS
// ──────────────────────────────────────────

const fetchAsBase64 = async (url) => {
  const response = await axios.get(url, {
    responseType: 'arraybuffer',
    timeout: 15000,
    maxContentLength: 10 * 1024 * 1024,
  });
  return Buffer.from(response.data).toString('base64');
};

const extractPdfText = async (url) => {
  try {
    const { default: pdfParse } = await import('pdf-parse/lib/pdf-parse.js');
    const response = await axios.get(url, { responseType: 'arraybuffer', timeout: 20000 });
    const buffer = Buffer.from(response.data);
    const result = await pdfParse(buffer);
    return result.text?.trim() || null;
  } catch (err) {
    console.warn('[AttachmentProcessor] pdf-parse unavailable/failed, falling back to raw text fetch:', err.message);
    return await fetchRawText(url);
  }
};

const fetchRawText = async (url) => {
  const response = await axios.get(url, {
    responseType: 'text',
    timeout: 10000,
    maxContentLength: 5 * 1024 * 1024,
  });
  return typeof response.data === 'string' ? response.data.trim() : null;
};
